In [19]:
import numpy as np
neuron = 4
def sigmoid(x):
    return 1.0/(1+ np.exp(-x))
def sigmoid_derivative(x):
    return x * (1.0 - x)

class NeuralNetwork:
    def __init__(self, x, y):
        self.input = x 
        print('inputs \n' , self.input)
        print()
        self.weights1 = np.random.rand(self.input.shape[1],neuron) #from x matrix 3x4 becouse 3 features
        print('weights1 \n',self.weights1) #for first layer
        print()
        self.weights2 = np.random.rand(neuron,1) # 1 3shan da l output w tale3 mn 4 neuron
        print('weights2 \n',self.weights2)
        print()
        self.y = y
        print('y \n',self.y)
        print()
        self.output = np.zeros(self.y.shape) # y hat
        print('output \n',self.output)  # bnfs shape l y
    

    def feedforward(self):
        self.layer1 = sigmoid(np.dot(self.input, self.weights1))
        print('layer 1 \n',self.layer1) #
        print() #
        self.output = sigmoid(np.dot(self.layer1, self.weights2))
        print('output \n',self.output) #


    def backprop(self):
        #application of the chain rule to find derivative of the loss function with respect to 
        #weights2 and weights1
        d_weights2 = np.dot(self.layer1.T, (2*(self.y - self.output) *
                    sigmoid_derivative(self.output)))
         #print('d_weights2 \n',d_weights2 )
         # )(print
        d_weights1 = np.dot(self.input.T,
             np.dot(2*(self.y - self.output) * sigmoid_derivative(self.output),
                    self.weights2.T) * sigmoid_derivative(self.layer1))
        print('d_weights1 \n',d_weights1) #
        
        # update the weights with the derivative (slope) of the loss function
        self.weights1 += d_weights1
        self.weights2 += d_weights2
           
X = np.array([[0,0,1],
                    [0,1,1],
                    [1,0,1],
                    [1,1,1]])


y = np.array([[0],
                [1], 
                [1],
                [0]])

nn = NeuralNetwork(X,y)
for i in range(10):
    nn.feedforward()
    nn.backprop()

print(nn.output)

inputs 
 [[0 0 1]
 [0 1 1]
 [1 0 1]
 [1 1 1]]

weights1 
 [[0.23036568 0.86711733 0.33593312 0.78255256]
 [0.19200426 0.30893681 0.66330129 0.23983724]
 [0.00792779 0.14131688 0.67088578 0.93424033]]

weights2 
 [[0.9024216 ]
 [0.03100725]
 [0.95473177]
 [0.11644163]]

y 
 [[0]
 [1]
 [1]
 [0]]

output 
 [[0.]
 [0.]
 [0.]
 [0.]]
layer 1 
 [[0.50198194 0.53527054 0.66170147 0.71793476]
 [0.54981718 0.61069955 0.79153238 0.76388127]
 [0.55929306 0.73271361 0.73239714 0.84771528]
 [0.60594476 0.78874398 0.84159184 0.87616779]]

output 
 [[0.76583514]
 [0.79571934]
 [0.79007702]
 [0.81408744]]
d_weights1 
 [[-0.03760947 -0.00085032 -0.0183349  -0.00206649]
 [-0.03826418 -0.0007836  -0.02090227 -0.00171843]
 [-0.08474301 -0.00247939 -0.06657621 -0.00714857]]
layer 1 
 [[0.48080563 0.53465373 0.64664165 0.71648489]
 [0.51922174 0.60992351 0.77672958 0.76227821]
 [0.52895282 0.732061   0.71543067 0.84652185]
 [0.56701461 0.78805778 0.82697048 0.87497665]]

output 
 [[0.62571732]
 [0.64621466]
